### PR TITLE
Create docker_build_stable

### PR DESCRIPTION
**Pull request by arbuilder**
Add docker build workflow

### CODE REVIEW

**Comment by arbuilder** [comment]
Needs to add on trigger for stable and create the same workflow for preview

**Comment by arbuilder** [comment]
@AriaMoradi Not sure if [published] includes draft releases, you can create a stable release then only we would know if it works

**Comment by AriaMoradi** [comment]
I'll hold up on this until we confirm it works.

**Comment by arbuilder** [comment]
> I'll hold up on this until we confirm it works.

It will work since preview triggers which is the same code u can merge it

**Pull request merged**
