### PR TITLE
Add Last Page Read offset

### PR DESCRIPTION
**Pull request by Syer10**
This is something I can use in JUI to go to the spot the person left the chapter at, exactly

### CODE REVIEW

**Comment by AriaMoradi** [comment]
what's the unit that offset is measured in? I proposed a float percentage value

**Comment by AriaMoradi** [comment]
Isn't this going to make the reader make too many update requests?

**Comment by Syer10** [comment]
> 
> 
> Isn't this going to make the reader make too many update requests?

I only send a update request when the window is closed, not sure how the WebUI does it



> 
> 
> what's the unit that offset is measured in? I proposed a float percentage value

It seems to be a unit thats set based the offset of the window compared to the top of the image, a quick test gave me 538 in compose. I dont believe I could make it work with a float percentage value as easily

**Comment by AriaMoradi** [comment]
> It seems to be a unit thats set based the offset of the window compared to the top of the image, a quick test gave me 538 in compose. I dont believe I could make it work with a float percentage value as easily

We have to find a cross implementation solution, either a percent offset or a real(not window) pixels from start offset

**Comment by Syer10** [comment]
Maybe we could find a way to store client data in the db per manga instead? Like some endpoints to store and request key value info per manga

**Comment by Syer10** [comment]
Maybe a table like this
```
--------------------------------
| key       | value | chapterRef |
| juioffset | 538   | 10         |
--------------------------------
```

**Comment by Syer10** [comment]
Superseded by https://github.com/Suwayomi/Tachidesk/pull/113

**Pull request closed without merging**
