### PR TITLE
Basic android.graphics Rect and Canvas implementation

### PR DESCRIPTION
**Pull request by animeavi**
Some extensions use more Canvas methods, but they don't really seem to get that far yet, all the others I was able to test seem to work now.

This fixes both extensions mentioned in #444 and a couple more I was able to test, in the future Canvas will need more stuff implemented but I can't even test that yet because the extensions have other problems and don't really get to those calls.

### CODE REVIEW

**Review by Syer10 — APPROVED** [review]

**Comment by Syer10** [comment]
Can you give a list of extensions you were able to get working and ones what you were not?

**Comment by animeavi** [comment]
> Can you give a list of extensions you were able to get working and ones what you were not?

I'll retest the others in a bit, I must have tested something in 禁漫天堂 / Jinman Tiantang that didn't use WEBP before cause that seems to be the problem now, I'll see if just bringing in the TwelveMonkeys WEBP library for ImageIO fixes it, since we already use it for JPEG anyway.

**Comment by animeavi** [comment]
Ok seems like some WEBPs from Jinman Tiantang can be decoded and some can't, I don't know if it's done on purpose or if it can be fixed, so I'd say that one partially works for now.

**Comment by animeavi** [comment]
From my tests of the extensions that use Canvas.

Working:
- MangaReader.to
- dmzj / 动漫之家 (looks like unimplemented Canvas is used for "comments" but not for getting pages)
- 肉漫屋 / Roumanwu
- Webtoons.com
- Web Comic Gamma(+ Plus)
- Flame Scans
- GigaViewer (tested Comic Days)
- Hentai2Read

Partially working:
- 禁漫天堂 / Jinman Tiantang (random WEBP decoding issue)

Not working:
- Viz Shonen Jump (`com.drew.imaging.ImageProcessingException`: File format could not be determined, uses unimplemented Canvas also)
- Tapas.io (some unimplemented cookie feature, uses unimplemented Canvas)
- xCaliBR Scans (`javax.net.ssl.SSLHandshakeException`: Received fatal alert: protocol_version)
- Japscan (some stub related to `android.os.Looper.getMainLooper`)

**Review by Syer10 — APPROVED** [review]
Sounds good 👍

**Pull request merged**
