### PR TITLE
Update publish.yml

### PR DESCRIPTION
**Pull request by arbuilder**
add docker build workflow

### CODE REVIEW

**Comment by arbuilder** [comment]
@AriaMoradi u have to create and add DOCKER_BUILD_ACCESS_TOKEN (public_repo scope will do) , github_token wont work (https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token)

**Comment by AriaMoradi** [comment]
secrets.DEPLOY_PREVIEW_TOKEN should have the perms, use that

**Comment by arbuilder** [comment]
> secrets.DEPLOY_PREVIEW_TOKEN should have the perms, use that

If u are sure about that I will just do that, since it would just need public_repo scope to run

**Comment by AriaMoradi** [comment]
I

> > secrets.DEPLOY_PREVIEW_TOKEN should have the perms, use that
> 
> If u are sure about that I will just do that, since it would just need public_repo scope to run

Yes, it hast that permission

**Pull request merged**
