### PR TITLE
Downloader Rewrite

### LINKED ISSUE #262: Rewrite Download Queue
- Testable design
- support operations
    - enqueue
    - unqueue
    - pause/stop
    - re-order
- use corutines
- parallel image downloading and smooth percentage
- parallel download jobs
- status websocket

### PR DESCRIPTION
**Pull request by Syer10**
- Rewrite downloader to use coroutines instead of a thread
- Remove unused Page functions
- Add page progress
- Add ProgressResponseBody
- Add support for canceling a download in the middle of downloading
- Fix clear download queue
- Reorder downloads
- Buffer the notify clients queue
- Download in parallel by source

closes #262

### CODE REVIEW

**Comment by AriaMoradi** [comment]
could we handle calling `notifyAllClients()` better? `step()` might hang or l if network is too slow?

**Comment by AriaMoradi** [comment]
We are missing the download queue re-order feature

And parallel page downloads

**Comment by Syer10** [comment]
Hmm I wasn't looking at that issue when I was working on this, Ill keep that in mind for later, I am working on a few things for JUI currently.

**Comment by Syer10** [comment]
Should have everything now 👍

**Pull request merged**
