### PR TITLE
Get Playwright working

### PR DESCRIPTION
**Pull request by Syer10**
ShadowJar works using a custom DriverJar implementation, it sets the `playwright.driver.impl` system property so Playwright looks there before trying to use its own.

The only actual change between this and the original file is that it catches `FileSystemAlreadyExistsException` and uses null instead

### CODE REVIEW

**Comment by Syer10** [comment]
Hmm, this seems to break the run gradle task, Ill see what I can do about that

**Comment by Syer10** [comment]
Its all good now, works with both run and shadowJar 👍

**Comment by AriaMoradi** [comment]
Let's see if they merge https://github.com/microsoft/playwright-java/pull/1140 upstream, if they refuse the patch then we'll merge this.

**Comment by Syer10** [comment]
It may be better to just merge it and remove the fix when Playwright merges it and does a release, since it may take a while before its merged.

**Pull request merged**
