### PR TITLE
the plural of Manga is Manga, not Mangas

### PR DESCRIPTION
**Pull request by KraXen72**

### CODE REVIEW

**Comment by AriaMoradi** [comment]
Plural of manga *is* mangas.

**Comment by AriaMoradi** [comment]
I'll merge because that reads better

**Comment by K0-RR** [comment]
Well technically there is no plural since this is a Japanese word
but it's commonly used in English so yeah both Manga and Mangas will be correct.

**Comment by K0-RR** [comment]
For reference, not that anyone asked
"In more general, commonly used, contexts, the plural form will also be manga. However, in more specific contexts, the plural form can also be mangas e.g. in reference to various types of mangas or a collection of mangas."
"With loan words, singular/plural distinction can be left as-is in the originating language, or English grammar rules can be applied to create a plural form. “Sheeps” is grammatically valid, but unusual."

So yeah just create an en_jp.json / en_jp.po or whatever format Tachidesk uses and make it use "Manga" as plural. There, everyone's happy.

**Pull request merged**
