### PR TITLE
[WIP] token auth

### PR DESCRIPTION
**Pull request by AriaMoradi**
The implementation is partial, up for grabs if anyone wants to continue.

Goals of the current implementation:
- Only handle single user mode.
- Potentially receive username and password from the config file(not the best idea?)
- have a "acquire (new) token" endpoint
- Check auth header compatible with [the standard HTTP way](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication) sample `Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b`
- Steal implementation details from [django rest framework's token auth](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication)

### CODE REVIEW

**Comment by Robonau** [comment]
> receive username and password from the config file

is usually a horrible idea to store the actual username and password in plain text at any time

**Comment by AdmnJ** [comment]
Would this get rid of "Re-auth" on every screen issue on some browsers? Just curious.

**Comment by Syer10** [comment]
It wouldnt

**Comment by AriaMoradi** [comment]
> Would this get rid of "Re-auth" on every screen issue on some browsers? Just curious.

For ipadOS and IOS browsers and any based on safari this would solve the issue.

**Comment by WantToLearnJapanese** [comment]
How's it going?

**Pull request closed without merging**
